FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

WORKDIR /var/www/frontend

RUN mkdir -p log
RUN mkdir -p public

COPY config/frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
