apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
        - name: DB_ADAPTER
          value: postgres
        - name: DB_HOST
          value: postgres-db
          #valueFrom:
          #  secretKeyRef:
          #    name: kongcreds
          #    key: postgresdbname
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: kong
        - name: DB_DATABASE
          value: konga
        - name: DB_PORT
          value: "5432"
        - name: KONGA_HOOK_TIMEOUT
          value: "120000"
        - name: NODE_ENV
          value: production
        - name: TOKEN_SECRET
          value: some_secret_token
        ports:
        - containerPort: 1337
          protocol: TCP
